INSERT INTO `hm_kiosques` (`id`, `nom_kiosque`, `dimension`, `status`) VALUES 
('', 'ANKORONDRANO à gauche jardin Henri Fraise', 2, 1),
('', 'ANALAMAHITSY Colyseum', 2, 1),
('', 'AMBODIMITA Dvt pont', 2, 1),
('', 'ANDROHIBE Pres Terminus Enam', 2, 1),
('', 'ROUTE DIGUE ART MALAGASY', 2, 1),
('', 'ANDRANOMENA Poste de Police', 1, 1),
('', 'Ankatso', 2, 1),
('', 'ANKADIMBAHOAKA', 2, 1),
('', 'TANJOMBATO Près arret bus Fce IKOPA CENTER', 2, 1),
('', 'MANAKAMBAHINY près arret bus FKT', 2, 1),
('', 'ANDREFAN\'AMBOHIJANAHARY (cimelta)', 2, 1),
('', 'ANDRANOBEVAVA', 2, 1),
('', 'AMPASAPITO GAMO', 2, 1),
('', 'TSARAMASAY', 2, 1),
('', 'AMPANDRIANOMBY Min Agri', 2, 1),
('', 'HOMI', 2, 1),
('', 'Ambatomainty', 2, 1),
('', 'AMBODIVONA FCE POSTE MEDICAL', 2, 1),
('', 'ANKADINDRAMAMY Fce Lycée privée vitale', 2, 1),
('', 'Meteo', 1, 1),
('', 'ANTANINANDRO Près escalier Behoririka Jovenna Rond point', 2, 1),
('', 'Besarety Mahavoky', 2, 1),
('', 'Avaradoha', 2, 1),
('', 'TSIAZOTAFO Croisement Behoririka descente vers CITIC', 2, 1),
('', 'ANTSAKAVIRO Près arret bus C UA fce Clin d\'œil', 2, 1),
('', 'ANKORAHOTRA Fce La gazette', 2, 1),
('', 'ANKORAHOTRA fce Pcie HANITRA', 2, 1),
('', 'ANTSAHABE (mascotte)', 2, 1),
('', 'Sampan Mahazoarivo', 2, 1),
('', 'MAHAZOARIVO près Ecole privee L\'EVEIL', 2, 1),
('', 'TSIMBAZAZA Fiv Pres PORTAIL COLLEGE DE France', 2, 1),
('', 'Ambohijatovo CT Jirama', 2, 1),
('', 'ANDOHALO Près EKAR', 2, 1),
('', 'AMPEFILOHA LTC Andavamamba Pres abri bus', 2, 1),
('', 'ANTSAHAVOLA Fce NJATO', 2, 1),
('', 'ROVA MANJAKAMIADANA', 1, 1),
('', 'MANDROSEZA près arret bus JIRAMA Bas Prinz Hotel', 1, 1),
('', 'MANDROSEZA avant pont', 2, 1),
('', 'AMBOHITSOA(ARRET MANDROSEZA)', 2, 1),
('', 'AMBOLOKANDRINA', 2, 1),
('', 'SOANIERANA CAPSAT', 2, 1),
('', 'Anosizato', 1, 1),
('', 'GARE ROUTIERE Fasan\'ny Karana', 2, 1),
('', '67 Ha MADA HOTEL', 1, 1),
('', 'ANTOHOMADINIKA HANGAR (taxi brousse Ambatondrazaka)', 2, 1),
('', 'ANTOHOMADINIKA (taxi brousse Mahitsy)', 2, 1),
('', 'ANOSIPATRANA', 2, 1),
('', 'COTONA PETITE VITESSE', 1, 1),
('', 'TRANON\'ISOTRY', 2, 1),
('', 'ANKORONDRANO TOUR ORANGE', 1, 1);